const roomsDetails = {
  "Living Room": {
    Room: "Living Room",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 48,
    "Measured Temperature": 25,
    "Measured Humidity": 50,
  },
  "Guest Room": {
    Room: "Guest Room",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 45,
    "Measured Temperature": 25,
    "Measured Humidity": 50,
  },
  "Kitchen Room": {
    Room: "Kitchen Room",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 45,
    "Measured Temperature": 25,
    "Measured Humidity": 50,
  },
  "Master Bedroom": {
    Room: "Master Bedroom",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 45,
    "Measured Temperature": 25,
    "Measured Humidity": 50,
  },
  Library: {
    Room: "Library",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 45,
    "Measured Temperature": 25,
    "Measured Humidity": 50,
  },
};

module.exports = roomsDetails;
